// File: catboard.v
// Generated by MyHDL 1.0dev
// Date: Wed Apr  4 14:42:23 2018


`timescale 1ns/10ps

module catboard (
    led,
    clock
);


output [3:0] led;
reg [3:0] led;
input clock;

reg reset;
reg toggle;
reg [26:0] cnt;



always @(posedge clock) begin: CATBOARD_RTL
    if (($signed({1'b0, cnt}) == (100000000 - 1))) begin
        cnt <= 0;
        toggle <= (!toggle);
    end
    else begin
        cnt <= (cnt + 1);
    end
end


always @(toggle) begin: CATBOARD_RTL_ASSIGN
    integer ii;
    led[0] = toggle;
    led[1] = (!toggle);
    for (ii=2; ii<4; ii=ii+1) begin
        led[ii] = 0;
    end
end


always @(posedge clock) begin: CATBOARD_RTL_RESET
    reset <= (!1'b0);
end

endmodule
